// Mocks generated by Mockito 5.0.7 from annotations
// in directus/test/src/mock/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i15;

import 'package:dio/src/adapter.dart' as _i7;
import 'package:dio/src/cancel_token.dart' as _i19;
import 'package:dio/src/dio.dart' as _i2;
import 'package:dio/src/interceptor.dart' as _i9;
import 'package:dio/src/options.dart' as _i6;
import 'package:dio/src/response.dart' as _i10;
import 'package:dio/src/transformer.dart' as _i8;
import 'package:directus/src/data_classes/directus_list_response.dart' as _i5;
import 'package:directus/src/data_classes/directus_response.dart' as _i4;
import 'package:directus/src/data_classes/directus_storage.dart' as _i11;
import 'package:directus/src/data_classes/filters.dart' as _i18;
import 'package:directus/src/data_classes/one_query.dart' as _i16;
import 'package:directus/src/data_classes/query.dart' as _i17;
import 'package:directus/src/modules/auth/_auth_fields.dart' as _i12;
import 'package:directus/src/modules/auth/_auth_response.dart' as _i13;
import 'package:directus/src/modules/auth/_auth_storage.dart' as _i20;
import 'package:directus/src/modules/items/items_converter.dart' as _i3;
import 'package:directus/src/modules/items/items_handler.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeDio extends _i1.Fake implements _i2.Dio {}

class _FakeItemsConverter<T> extends _i1.Fake implements _i3.ItemsConverter<T> {
}

class _FakeDirectusResponse<T> extends _i1.Fake
    implements _i4.DirectusResponse<T> {}

class _FakeDirectusListResponse<T> extends _i1.Fake
    implements _i5.DirectusListResponse<T> {}

class _FakeBaseOptions extends _i1.Fake implements _i6.BaseOptions {}

class _FakeHttpClientAdapter extends _i1.Fake implements _i7.HttpClientAdapter {
}

class _FakeTransformer extends _i1.Fake implements _i8.Transformer {}

class _FakeInterceptors extends _i1.Fake implements _i9.Interceptors {}

class _FakeResponse<T> extends _i1.Fake implements _i10.Response<T> {}

class _FakeDirectusStorage extends _i1.Fake implements _i11.DirectusStorage {}

class _FakeAuthFields extends _i1.Fake implements _i12.AuthFields {}

class _FakeAuthResponse extends _i1.Fake implements _i13.AuthResponse {}

/// A class which mocks [ItemsHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsHandler<T> extends _i1.Mock implements _i14.ItemsHandler<T> {
  MockItemsHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get client =>
      (super.noSuchMethod(Invocation.getter(#client), returnValue: _FakeDio())
          as _i2.Dio);
  @override
  set client(_i2.Dio? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  _i3.ItemsConverter<dynamic> get converter =>
      (super.noSuchMethod(Invocation.getter(#converter),
              returnValue: _FakeItemsConverter<dynamic>())
          as _i3.ItemsConverter<dynamic>);
  @override
  set converter(_i3.ItemsConverter<dynamic>? _converter) =>
      super.noSuchMethod(Invocation.setter(#converter, _converter),
          returnValueForMissingStub: null);
  @override
  _i15.Future<_i4.DirectusResponse<T>> readOne(String? id,
          {_i16.OneQuery? query}) =>
      (super.noSuchMethod(Invocation.method(#readOne, [id], {#query: query}),
              returnValue: Future<_i4.DirectusResponse<T>>.value(
                  _FakeDirectusResponse<T>()))
          as _i15.Future<_i4.DirectusResponse<T>>);
  @override
  _i15.Future<_i5.DirectusListResponse<T>> readMany(
          {_i17.Query? query, _i18.Filters? filters}) =>
      (super.noSuchMethod(
          Invocation.method(#readMany, [], {#query: query, #filters: filters}),
          returnValue: Future<_i5.DirectusListResponse<T>>.value(
              _FakeDirectusListResponse<T>())) as _i15
          .Future<_i5.DirectusListResponse<T>>);
  @override
  _i15.Future<_i4.DirectusResponse<T>> createOne(T? data) =>
      (super.noSuchMethod(Invocation.method(#createOne, [data]),
              returnValue: Future<_i4.DirectusResponse<T>>.value(
                  _FakeDirectusResponse<T>()))
          as _i15.Future<_i4.DirectusResponse<T>>);
  @override
  _i15.Future<_i5.DirectusListResponse<T>> createMany(List<T>? data) =>
      (super.noSuchMethod(Invocation.method(#createMany, [data]),
              returnValue: Future<_i5.DirectusListResponse<T>>.value(
                  _FakeDirectusListResponse<T>()))
          as _i15.Future<_i5.DirectusListResponse<T>>);
  @override
  _i15.Future<_i4.DirectusResponse<T>> updateOne({T? data, String? id}) =>
      (super.noSuchMethod(
              Invocation.method(#updateOne, [], {#data: data, #id: id}),
              returnValue: Future<_i4.DirectusResponse<T>>.value(
                  _FakeDirectusResponse<T>()))
          as _i15.Future<_i4.DirectusResponse<T>>);
  @override
  _i15.Future<_i5.DirectusListResponse<T>> updateMany(
          {List<String>? ids, T? data}) =>
      (super.noSuchMethod(
              Invocation.method(#updateMany, [], {#ids: ids, #data: data}),
              returnValue: Future<_i5.DirectusListResponse<T>>.value(
                  _FakeDirectusListResponse<T>()))
          as _i15.Future<_i5.DirectusListResponse<T>>);
  @override
  _i15.Future<void> deleteOne(String? id) =>
      (super.noSuchMethod(Invocation.method(#deleteOne, [id]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i15.Future<void>);
  @override
  _i15.Future<void> deleteMany(List<String>? ids) =>
      (super.noSuchMethod(Invocation.method(#deleteMany, [ids]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i15.Future<void>);
}

/// A class which mocks [DirectusStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectusStorage extends _i1.Mock implements _i11.DirectusStorage {
  MockDirectusStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<void> setItem(String? key, dynamic value) =>
      (super.noSuchMethod(Invocation.method(#setItem, [key, value]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i15.Future<void>);
  @override
  _i15.Future<dynamic> getItem(String? key) =>
      (super.noSuchMethod(Invocation.method(#getItem, [key]),
          returnValue: Future<dynamic>.value(null)) as _i15.Future<dynamic>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i2.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BaseOptions get options =>
      (super.noSuchMethod(Invocation.getter(#options),
          returnValue: _FakeBaseOptions()) as _i6.BaseOptions);
  @override
  set options(_i6.BaseOptions? _options) =>
      super.noSuchMethod(Invocation.setter(#options, _options),
          returnValueForMissingStub: null);
  @override
  _i7.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(Invocation.getter(#httpClientAdapter),
          returnValue: _FakeHttpClientAdapter()) as _i7.HttpClientAdapter);
  @override
  set httpClientAdapter(_i7.HttpClientAdapter? _httpClientAdapter) => super
      .noSuchMethod(Invocation.setter(#httpClientAdapter, _httpClientAdapter),
          returnValueForMissingStub: null);
  @override
  _i8.Transformer get transformer =>
      (super.noSuchMethod(Invocation.getter(#transformer),
          returnValue: _FakeTransformer()) as _i8.Transformer);
  @override
  set transformer(_i8.Transformer? _transformer) =>
      super.noSuchMethod(Invocation.setter(#transformer, _transformer),
          returnValueForMissingStub: null);
  @override
  _i9.Interceptors get interceptors =>
      (super.noSuchMethod(Invocation.getter(#interceptors),
          returnValue: _FakeInterceptors()) as _i9.Interceptors);
  @override
  void close({bool? force = false}) =>
      super.noSuchMethod(Invocation.method(#close, [], {#force: force}),
          returnValueForMissingStub: null);
  @override
  _i15.Future<_i10.Response<T>> get<T>(String? path,
          {Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [
                path
              ], {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> getUri<T>(Uri? uri,
          {_i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#getUri, [
                uri
              ], {
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> post<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> postUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#postUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> put<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> putUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#putUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> head<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i19.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#head, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> headUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i19.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#headUri, [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken}),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> delete<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i19.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> deleteUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i19.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteUri, [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken}),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> patch<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> patchUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i19.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#patchUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  void lock() => super.noSuchMethod(Invocation.method(#lock, []),
      returnValueForMissingStub: null);
  @override
  void unlock() => super.noSuchMethod(Invocation.method(#unlock, []),
      returnValueForMissingStub: null);
  @override
  void clear() => super.noSuchMethod(Invocation.method(#clear, []),
      returnValueForMissingStub: null);
  @override
  _i15.Future<_i10.Response<dynamic>> download(
          String? urlPath, dynamic savePath,
          {_i6.ProgressCallback? onReceiveProgress,
          Map<String, dynamic>? queryParameters,
          _i19.CancelToken? cancelToken,
          bool? deleteOnError = true,
          String? lengthHeader = r'content-length',
          dynamic data,
          _i6.Options? options}) =>
      (super.noSuchMethod(
              Invocation.method(#download, [
                urlPath,
                savePath
              ], {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options
              }),
              returnValue: Future<_i10.Response<dynamic>>.value(
                  _FakeResponse<dynamic>()))
          as _i15.Future<_i10.Response<dynamic>>);
  @override
  _i15.Future<_i10.Response<dynamic>> downloadUri(Uri? uri, dynamic savePath,
          {_i6.ProgressCallback? onReceiveProgress,
          _i19.CancelToken? cancelToken,
          bool? deleteOnError = true,
          String? lengthHeader = r'content-length',
          dynamic data,
          _i6.Options? options}) =>
      (super.noSuchMethod(
              Invocation.method(#downloadUri, [
                uri,
                savePath
              ], {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options
              }),
              returnValue: Future<_i10.Response<dynamic>>.value(
                  _FakeResponse<dynamic>()))
          as _i15.Future<_i10.Response<dynamic>>);
  @override
  _i15.Future<_i10.Response<T>> request<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i19.CancelToken? cancelToken,
          _i6.Options? options,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#request, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> requestUri<T>(Uri? uri,
          {dynamic data,
          _i19.CancelToken? cancelToken,
          _i6.Options? options,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#requestUri, [
                uri
              ], {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
  @override
  _i15.Future<_i10.Response<T>> fetch<T>(_i6.RequestOptions? requestOptions) =>
      (super.noSuchMethod(Invocation.method(#fetch, [requestOptions]),
              returnValue: Future<_i10.Response<T>>.value(_FakeResponse<T>()))
          as _i15.Future<_i10.Response<T>>);
}

/// A class which mocks [BaseOptions].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseOptions extends _i1.Mock implements _i6.BaseOptions {
  MockBaseOptions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get setRequestContentTypeWhenNoPayload => (super.noSuchMethod(
      Invocation.getter(#setRequestContentTypeWhenNoPayload),
      returnValue: false) as bool);
  @override
  set setRequestContentTypeWhenNoPayload(
          bool? _setRequestContentTypeWhenNoPayload) =>
      super.noSuchMethod(
          Invocation.setter(#setRequestContentTypeWhenNoPayload,
              _setRequestContentTypeWhenNoPayload),
          returnValueForMissingStub: null);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  set baseUrl(String? _baseUrl) =>
      super.noSuchMethod(Invocation.setter(#baseUrl, _baseUrl),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> get queryParameters =>
      (super.noSuchMethod(Invocation.getter(#queryParameters),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  set queryParameters(Map<String, dynamic>? _queryParameters) =>
      super.noSuchMethod(Invocation.setter(#queryParameters, _queryParameters),
          returnValueForMissingStub: null);
  @override
  int get connectTimeout =>
      (super.noSuchMethod(Invocation.getter(#connectTimeout), returnValue: 0)
          as int);
  @override
  set connectTimeout(int? _connectTimeout) =>
      super.noSuchMethod(Invocation.setter(#connectTimeout, _connectTimeout),
          returnValueForMissingStub: null);
  @override
  String get method =>
      (super.noSuchMethod(Invocation.getter(#method), returnValue: '')
          as String);
  @override
  set method(String? _method) =>
      super.noSuchMethod(Invocation.setter(#method, _method),
          returnValueForMissingStub: null);
  @override
  int get sendTimeout =>
      (super.noSuchMethod(Invocation.getter(#sendTimeout), returnValue: 0)
          as int);
  @override
  set sendTimeout(int? _sendTimeout) =>
      super.noSuchMethod(Invocation.setter(#sendTimeout, _sendTimeout),
          returnValueForMissingStub: null);
  @override
  int get receiveTimeout =>
      (super.noSuchMethod(Invocation.getter(#receiveTimeout), returnValue: 0)
          as int);
  @override
  set receiveTimeout(int? _receiveTimeout) =>
      super.noSuchMethod(Invocation.setter(#receiveTimeout, _receiveTimeout),
          returnValueForMissingStub: null);
  @override
  _i6.ResponseType get responseType =>
      (super.noSuchMethod(Invocation.getter(#responseType),
          returnValue: _i6.ResponseType.json) as _i6.ResponseType);
  @override
  set responseType(_i6.ResponseType? _responseType) =>
      super.noSuchMethod(Invocation.setter(#responseType, _responseType),
          returnValueForMissingStub: null);
  @override
  _i6.ValidateStatus get validateStatus =>
      (super.noSuchMethod(Invocation.getter(#validateStatus),
          returnValue: (int? status) => false) as _i6.ValidateStatus);
  @override
  set validateStatus(_i6.ValidateStatus? _validateStatus) =>
      super.noSuchMethod(Invocation.setter(#validateStatus, _validateStatus),
          returnValueForMissingStub: null);
  @override
  bool get receiveDataWhenStatusError =>
      (super.noSuchMethod(Invocation.getter(#receiveDataWhenStatusError),
          returnValue: false) as bool);
  @override
  set receiveDataWhenStatusError(bool? _receiveDataWhenStatusError) =>
      super.noSuchMethod(
          Invocation.setter(
              #receiveDataWhenStatusError, _receiveDataWhenStatusError),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> get extra =>
      (super.noSuchMethod(Invocation.getter(#extra),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  set extra(Map<String, dynamic>? _extra) =>
      super.noSuchMethod(Invocation.setter(#extra, _extra),
          returnValueForMissingStub: null);
  @override
  bool get followRedirects => (super
          .noSuchMethod(Invocation.getter(#followRedirects), returnValue: false)
      as bool);
  @override
  set followRedirects(bool? _followRedirects) =>
      super.noSuchMethod(Invocation.setter(#followRedirects, _followRedirects),
          returnValueForMissingStub: null);
  @override
  int get maxRedirects =>
      (super.noSuchMethod(Invocation.getter(#maxRedirects), returnValue: 0)
          as int);
  @override
  set maxRedirects(int? _maxRedirects) =>
      super.noSuchMethod(Invocation.setter(#maxRedirects, _maxRedirects),
          returnValueForMissingStub: null);
  @override
  set requestEncoder(_i6.RequestEncoder? _requestEncoder) =>
      super.noSuchMethod(Invocation.setter(#requestEncoder, _requestEncoder),
          returnValueForMissingStub: null);
  @override
  set responseDecoder(_i6.ResponseDecoder? _responseDecoder) =>
      super.noSuchMethod(Invocation.setter(#responseDecoder, _responseDecoder),
          returnValueForMissingStub: null);
  @override
  _i6.ListFormat get listFormat =>
      (super.noSuchMethod(Invocation.getter(#listFormat),
          returnValue: _i6.ListFormat.csv) as _i6.ListFormat);
  @override
  set listFormat(_i6.ListFormat? _listFormat) =>
      super.noSuchMethod(Invocation.setter(#listFormat, _listFormat),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> get headers =>
      (super.noSuchMethod(Invocation.getter(#headers),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  set headers(Map<String, dynamic>? headers) =>
      super.noSuchMethod(Invocation.setter(#headers, headers),
          returnValueForMissingStub: null);
  @override
  set contentType(String? contentType) =>
      super.noSuchMethod(Invocation.setter(#contentType, contentType),
          returnValueForMissingStub: null);
  @override
  _i6.BaseOptions copyWith(
          {String? method,
          String? baseUrl,
          Map<String, dynamic>? queryParameters,
          String? path,
          int? connectTimeout,
          int? receiveTimeout,
          int? sendTimeout,
          Map<String, dynamic>? extra,
          Map<String, dynamic>? headers,
          _i6.ResponseType? responseType,
          String? contentType,
          _i6.ValidateStatus? validateStatus,
          bool? receiveDataWhenStatusError,
          bool? followRedirects,
          int? maxRedirects,
          _i6.RequestEncoder? requestEncoder,
          _i6.ResponseDecoder? responseDecoder,
          _i6.ListFormat? listFormat,
          bool? setRequestContentTypeWhenNoPayload}) =>
      (super.noSuchMethod(
          Invocation.method(#copyWith, [], {
            #method: method,
            #baseUrl: baseUrl,
            #queryParameters: queryParameters,
            #path: path,
            #connectTimeout: connectTimeout,
            #receiveTimeout: receiveTimeout,
            #sendTimeout: sendTimeout,
            #extra: extra,
            #headers: headers,
            #responseType: responseType,
            #contentType: contentType,
            #validateStatus: validateStatus,
            #receiveDataWhenStatusError: receiveDataWhenStatusError,
            #followRedirects: followRedirects,
            #maxRedirects: maxRedirects,
            #requestEncoder: requestEncoder,
            #responseDecoder: responseDecoder,
            #listFormat: listFormat,
            #setRequestContentTypeWhenNoPayload:
                setRequestContentTypeWhenNoPayload
          }),
          returnValue: _FakeBaseOptions()) as _i6.BaseOptions);
  @override
  String? contentTypeWithRequestBody(String? method) => (super.noSuchMethod(
      Invocation.method(#contentTypeWithRequestBody, [method])) as String?);
}

/// A class which mocks [AuthStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorage extends _i1.Mock implements _i20.AuthStorage {
  MockAuthStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.DirectusStorage get storage =>
      (super.noSuchMethod(Invocation.getter(#storage),
          returnValue: _FakeDirectusStorage()) as _i11.DirectusStorage);
  @override
  set storage(_i11.DirectusStorage? _storage) =>
      super.noSuchMethod(Invocation.setter(#storage, _storage),
          returnValueForMissingStub: null);
  @override
  _i12.AuthFields get fields => (super.noSuchMethod(Invocation.getter(#fields),
      returnValue: _FakeAuthFields()) as _i12.AuthFields);
  @override
  set fields(_i12.AuthFields? _fields) =>
      super.noSuchMethod(Invocation.setter(#fields, _fields),
          returnValueForMissingStub: null);
  @override
  _i15.Future<void> storeLoginData(_i13.AuthResponse? data) =>
      (super.noSuchMethod(Invocation.method(#storeLoginData, [data]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i15.Future<void>);
  @override
  _i15.Future<_i13.AuthResponse?> getLoginData() => (super.noSuchMethod(
          Invocation.method(#getLoginData, []),
          returnValue: Future<_i13.AuthResponse?>.value(_FakeAuthResponse()))
      as _i15.Future<_i13.AuthResponse?>);
}
