// Mocks generated by Mockito 5.0.0 from annotations
// in directus/test/src/mock/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i12;

import 'package:dio/src/adapter.dart' as _i7;
import 'package:dio/src/cancel_token.dart' as _i16;
import 'package:dio/src/dio.dart' as _i2;
import 'package:dio/src/interceptor.dart' as _i9;
import 'package:dio/src/options.dart' as _i6;
import 'package:dio/src/response.dart' as _i10;
import 'package:dio/src/transformer.dart' as _i8;
import 'package:directus/src/data_classes/directus_list_response.dart' as _i5;
import 'package:directus/src/data_classes/directus_response.dart' as _i4;
import 'package:directus/src/data_classes/directus_storage.dart' as _i17;
import 'package:directus/src/data_classes/filters.dart' as _i15;
import 'package:directus/src/data_classes/one_query.dart' as _i13;
import 'package:directus/src/data_classes/query.dart' as _i14;
import 'package:directus/src/modules/items/items_converter.dart' as _i3;
import 'package:directus/src/modules/items/items_handler.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeDio extends _i1.Fake implements _i2.Dio {}

class _FakeItemsConverter<T> extends _i1.Fake implements _i3.ItemsConverter<T> {
}

class _FakeDirectusResponse<T> extends _i1.Fake
    implements _i4.DirectusResponse<T> {}

class _FakeDirectusListResponse<T> extends _i1.Fake
    implements _i5.DirectusListResponse<T> {}

class _FakeBaseOptions extends _i1.Fake implements _i6.BaseOptions {}

class _FakeHttpClientAdapter extends _i1.Fake implements _i7.HttpClientAdapter {
}

class _FakeTransformer extends _i1.Fake implements _i8.Transformer {}

class _FakeInterceptors extends _i1.Fake implements _i9.Interceptors {}

class _FakeResponse<T> extends _i1.Fake implements _i10.Response<T> {}

/// A class which mocks [ItemsHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsHandler<T> extends _i1.Mock implements _i11.ItemsHandler<T> {
  MockItemsHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get client =>
      (super.noSuchMethod(Invocation.getter(#client), returnValue: _FakeDio())
          as _i2.Dio);
  @override
  set client(_i2.Dio? _client) =>
      super.noSuchMethod(Invocation.setter(#client, _client),
          returnValueForMissingStub: null);
  @override
  _i3.ItemsConverter<dynamic> get converter =>
      (super.noSuchMethod(Invocation.getter(#converter),
              returnValue: _FakeItemsConverter<dynamic>())
          as _i3.ItemsConverter<dynamic>);
  @override
  set converter(_i3.ItemsConverter<dynamic>? _converter) =>
      super.noSuchMethod(Invocation.setter(#converter, _converter),
          returnValueForMissingStub: null);
  @override
  _i12.Future<_i4.DirectusResponse<T>> readOne(String? id,
          {_i13.OneQuery? query}) =>
      (super.noSuchMethod(Invocation.method(#readOne, [id], {#query: query}),
              returnValue: Future.value(_FakeDirectusResponse<T>()))
          as _i12.Future<_i4.DirectusResponse<T>>);
  @override
  _i12.Future<_i5.DirectusListResponse<T>> readMany(
          {_i14.Query? query, _i15.Filters? filters}) =>
      (super.noSuchMethod(
          Invocation.method(#readMany, [], {#query: query, #filters: filters}),
          returnValue:
              Future.value(_FakeDirectusListResponse<T>())) as _i12
          .Future<_i5.DirectusListResponse<T>>);
  @override
  _i12.Future<_i4.DirectusResponse<T>> createOne(T? data) =>
      (super.noSuchMethod(Invocation.method(#createOne, [data]),
              returnValue: Future.value(_FakeDirectusResponse<T>()))
          as _i12.Future<_i4.DirectusResponse<T>>);
  @override
  _i12.Future<_i5.DirectusListResponse<T>> createMany(List<T>? data) =>
      (super.noSuchMethod(Invocation.method(#createMany, [data]),
              returnValue: Future.value(_FakeDirectusListResponse<T>()))
          as _i12.Future<_i5.DirectusListResponse<T>>);
  @override
  _i12.Future<_i4.DirectusResponse<T>> updateOne({T? data, String? id}) =>
      (super.noSuchMethod(
              Invocation.method(#updateOne, [], {#data: data, #id: id}),
              returnValue: Future.value(_FakeDirectusResponse<T>()))
          as _i12.Future<_i4.DirectusResponse<T>>);
  @override
  _i12.Future<_i5.DirectusListResponse<T>> updateMany(
          {List<String>? ids, T? data}) =>
      (super.noSuchMethod(
              Invocation.method(#updateMany, [], {#ids: ids, #data: data}),
              returnValue: Future.value(_FakeDirectusListResponse<T>()))
          as _i12.Future<_i5.DirectusListResponse<T>>);
  @override
  _i12.Future<void> deleteOne(String? id) =>
      (super.noSuchMethod(Invocation.method(#deleteOne, [id]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i12.Future<void>);
  @override
  _i12.Future<void> deleteMany(List<String>? ids) =>
      (super.noSuchMethod(Invocation.method(#deleteMany, [ids]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i12.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i2.Dio {
  @override
  _i6.BaseOptions get options =>
      (super.noSuchMethod(Invocation.getter(#options),
          returnValue: _FakeBaseOptions()) as _i6.BaseOptions);
  @override
  set options(_i6.BaseOptions? _options) =>
      super.noSuchMethod(Invocation.setter(#options, _options),
          returnValueForMissingStub: null);
  @override
  _i7.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(Invocation.getter(#httpClientAdapter),
          returnValue: _FakeHttpClientAdapter()) as _i7.HttpClientAdapter);
  @override
  set httpClientAdapter(_i7.HttpClientAdapter? _httpClientAdapter) => super
      .noSuchMethod(Invocation.setter(#httpClientAdapter, _httpClientAdapter),
          returnValueForMissingStub: null);
  @override
  _i8.Transformer get transformer =>
      (super.noSuchMethod(Invocation.getter(#transformer),
          returnValue: _FakeTransformer()) as _i8.Transformer);
  @override
  set transformer(_i8.Transformer? _transformer) =>
      super.noSuchMethod(Invocation.setter(#transformer, _transformer),
          returnValueForMissingStub: null);
  @override
  _i9.Interceptors get interceptors =>
      (super.noSuchMethod(Invocation.getter(#interceptors),
          returnValue: _FakeInterceptors()) as _i9.Interceptors);
  @override
  void close({bool? force = false}) =>
      super.noSuchMethod(Invocation.method(#close, [], {#force: force}),
          returnValueForMissingStub: null);
  @override
  _i12.Future<_i10.Response<T>> get<T>(String? path,
          {Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#get, [
                path
              ], {
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> getUri<T>(Uri? uri,
          {_i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#getUri, [
                uri
              ], {
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> post<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> postUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#postUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> put<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> putUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#putUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> head<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i16.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#head, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> headUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i16.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#headUri, [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken}),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> delete<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i16.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> deleteUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i16.CancelToken? cancelToken}) =>
      (super.noSuchMethod(
              Invocation.method(#deleteUri, [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken}),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> patch<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> patchUri<T>(Uri? uri,
          {dynamic data,
          _i6.Options? options,
          _i16.CancelToken? cancelToken,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#patchUri, [
                uri
              ], {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> resolve<T>(dynamic response) =>
      (super.noSuchMethod(Invocation.method(#resolve, [response]),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> reject<T>(dynamic err) =>
      (super.noSuchMethod(Invocation.method(#reject, [err]),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<dynamic>> download(
          String? urlPath, dynamic savePath,
          {_i6.ProgressCallback? onReceiveProgress,
          Map<String, dynamic>? queryParameters,
          _i16.CancelToken? cancelToken,
          bool? deleteOnError = true,
          String? lengthHeader = r'content-length',
          dynamic data,
          _i6.Options? options}) =>
      (super.noSuchMethod(
              Invocation.method(#download, [
                urlPath,
                savePath
              ], {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options
              }),
              returnValue: Future.value(_FakeResponse<dynamic>()))
          as _i12.Future<_i10.Response<dynamic>>);
  @override
  _i12.Future<_i10.Response<dynamic>> downloadUri(Uri? uri, dynamic savePath,
          {_i6.ProgressCallback? onReceiveProgress,
          _i16.CancelToken? cancelToken,
          bool? deleteOnError = true,
          String? lengthHeader = r'content-length',
          dynamic data,
          _i6.Options? options}) =>
      (super.noSuchMethod(
              Invocation.method(#downloadUri, [
                uri,
                savePath
              ], {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options
              }),
              returnValue: Future.value(_FakeResponse<dynamic>()))
          as _i12.Future<_i10.Response<dynamic>>);
  @override
  _i12.Future<_i10.Response<T>> request<T>(String? path,
          {dynamic data,
          Map<String, dynamic>? queryParameters,
          _i16.CancelToken? cancelToken,
          _i6.Options? options,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#request, [
                path
              ], {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> requestUri<T>(Uri? uri,
          {dynamic data,
          _i16.CancelToken? cancelToken,
          _i6.Options? options,
          _i6.ProgressCallback? onSendProgress,
          _i6.ProgressCallback? onReceiveProgress}) =>
      (super.noSuchMethod(
              Invocation.method(#requestUri, [
                uri
              ], {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress
              }),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
  @override
  _i12.Future<_i10.Response<T>> fetch<T>(_i6.RequestOptions? requestOptions) =>
      (super.noSuchMethod(Invocation.method(#fetch, [requestOptions]),
              returnValue: Future.value(_FakeResponse<T>()))
          as _i12.Future<_i10.Response<T>>);
}

/// A class which mocks [DirectusStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectusStorage extends _i1.Mock implements _i17.DirectusStorage {
  @override
  _i12.Future<void> setItem(String? key, dynamic value) =>
      (super.noSuchMethod(Invocation.method(#setItem, [key, value]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i12.Future<void>);
  @override
  _i12.Future<dynamic> getItem(String? key) =>
      (super.noSuchMethod(Invocation.method(#getItem, [key]),
          returnValue: Future.value(null)) as _i12.Future<dynamic>);
}
